version: '3'

services:
  api-internal-iot:
    image: davidcuy/makeriot-internal-api:dev
    container_name: api-internal-iot
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo-local:
        condition: service_healthy
    env_file:
      - ./.services/api-internal/.env
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - 5000:5000
    volumes: 
      - './.services/server/conf:/code/conf'
      - './.volumes/db:/code/db'
      - './.volumes/server/storage:/code/api/storage/local'
      - './.volumes/server/credentials/server:/code/api/storage/credentials/server'
      - './.volumes/server/credentials/clients:/code/api/storage/credentials/clients'
  mongo-local:
    image: mongo:7.0.1
    container_name: mongo-local
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo-local:27017/local --quiet
      interval: 10s
      timeout: 10s
      retries: 7
      start_period: 50s
    env_file:
      - ./.services/mongo/.env
    volumes: 
      - './.volumes/mongo:/data/db'
  
  mongo-express:
    image: mongo-express:1.0.0-alpha
    container_name: mongo-express
    depends_on:
      mongo-local:
        condition: service_healthy
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ./.services/mongo-express/.env
  mosquitto:
    image: eclipse-mosquitto:2.0.14
    hostname: mosquitto
    volumes:
      - ./.services/mosquitto:/mosquitto
      #- ./volumes/server/credentials/server:/mosquitto/certs
    expose:
        - "8883"
        - "9001"
    ports:
        - "8883:8883"
        - "9001:9001"

  backbackground-services:
    image: davidcuy/makeriot-background-services:dev
    container_name: background-services
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo-local:
        condition: service_healthy
    restart: always
    env_file:
      - ./.services/background-services/.env
    environment:
      PYTHONUNBUFFERED: 1
  
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - 9890:15672
    hostname: stats
    volumes:
      - ./.volumes/rabbitmq/data:/var/lib/rabbitmq/mnesia
      - type: bind
        source: ./.volumes/rabbitmq/rabbitmq-enabled-plugins
        target: /etc/rabbitmq/enabled_plugins
      - type: bind
        source: ./.volumes/rabbitmq/rabbitmq.config
        target: /etc/rabbitmq/rabbitmq.config
      - type: bind
        source: ./.volumes/rabbitmq/rabbitmq-defs.json
        target: /etc/rabbitmq/rabbitmq-defs.json
  